/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ContainerTag {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PrimaryButton {
        "type": string;
    }
}
declare global {
    interface HTMLContainerTagElement extends Components.ContainerTag, HTMLStencilElement {
    }
    var HTMLContainerTagElement: {
        prototype: HTMLContainerTagElement;
        new (): HTMLContainerTagElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPrimaryButtonElement extends Components.PrimaryButton, HTMLStencilElement {
    }
    var HTMLPrimaryButtonElement: {
        prototype: HTMLPrimaryButtonElement;
        new (): HTMLPrimaryButtonElement;
    };
    interface HTMLElementTagNameMap {
        "container-tag": HTMLContainerTagElement;
        "my-component": HTMLMyComponentElement;
        "primary-button": HTMLPrimaryButtonElement;
    }
}
declare namespace LocalJSX {
    interface ContainerTag {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PrimaryButton {
        "type"?: string;
    }
    interface IntrinsicElements {
        "container-tag": ContainerTag;
        "my-component": MyComponent;
        "primary-button": PrimaryButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "container-tag": LocalJSX.ContainerTag & JSXBase.HTMLAttributes<HTMLContainerTagElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "primary-button": LocalJSX.PrimaryButton & JSXBase.HTMLAttributes<HTMLPrimaryButtonElement>;
        }
    }
}
